--------------------------------------------------------
--  文件已创建 - 星期五-十一月-23-2018
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ECHARTS_OPTION
--------------------------------------------------------

  CREATE TABLE "WJZ"."ECHARTS_OPTION"
   (	"ID" NUMBER(*,0),
	"NAME" VARCHAR2(200 BYTE),
	"REMARK" VARCHAR2(500 BYTE),
	"STATUS" VARCHAR2(1 BYTE) DEFAULT 0,
	"CREATE_TIME" VARCHAR2(20 BYTE),
	"OPTION_JSON" CLOB,
	"OPTION_SCRIPT" CLOB,
	"Y_TYPE" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
 LOB ("OPTION_JSON") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
  NOCACHE LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT))
 LOB ("OPTION_SCRIPT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
  NOCACHE LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;


   COMMENT ON COLUMN "WJZ"."ECHARTS_OPTION"."ID" IS '编号';

   COMMENT ON COLUMN "WJZ"."ECHARTS_OPTION"."NAME" IS '名称';

   COMMENT ON COLUMN "WJZ"."ECHARTS_OPTION"."REMARK" IS '描述';

   COMMENT ON COLUMN "WJZ"."ECHARTS_OPTION"."STATUS" IS '状态(1;启用,0:禁用)';

   COMMENT ON COLUMN "WJZ"."ECHARTS_OPTION"."CREATE_TIME" IS '创建时间';

   COMMENT ON COLUMN "WJZ"."ECHARTS_OPTION"."OPTION_JSON" IS 'json';

   COMMENT ON COLUMN "WJZ"."ECHARTS_OPTION"."OPTION_SCRIPT" IS '脚本';

   COMMENT ON COLUMN "WJZ"."ECHARTS_OPTION"."Y_TYPE" IS '0;系统默认,1;用户自定义';
--------------------------------------------------------
--  DDL for Index E_OPTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WJZ"."E_OPTION_PK" ON "WJZ"."ECHARTS_OPTION" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ECHARTS_OPTION
--------------------------------------------------------

  ALTER TABLE "WJZ"."ECHARTS_OPTION" ADD CONSTRAINT "E_OPTION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;

  ALTER TABLE "WJZ"."ECHARTS_OPTION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger TRIG_ECHARTS_OPTION
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WJZ"."TRIG_ECHARTS_OPTION"
   before insert on "WJZ"."ECHARTS_OPTION"
   for each row
begin
   if inserting then
      if :NEW."ID" is null then
         select S_ECHARTS_OPTION.nextval into :NEW."ID" from dual;
      end if;
   end if;
end;


/
ALTER TRIGGER "WJZ"."TRIG_ECHARTS_OPTION" ENABLE;

--------------------------------------------------------
--  DDL for Table ECHARTS_SQL
--------------------------------------------------------

  CREATE TABLE "WJZ"."ECHARTS_SQL"
   (	"ID" NUMBER(*,0),
	"OPT_ID" NUMBER(*,0),
	"NAME" VARCHAR2(200 BYTE),
	"TYPE" VARCHAR2(20 BYTE),
	"SQL" VARCHAR2(4000 BYTE),
	"STATUS" VARCHAR2(1 BYTE) DEFAULT 0,
	"CREATE_TIME" VARCHAR2(20 BYTE),
	"SORT" NUMBER(*,0),
	"RADIUS" VARCHAR2(50 BYTE),
	"SQL_PARAM" VARCHAR2(500 BYTE),
	"Y_TYPE" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


   COMMENT ON COLUMN "WJZ"."ECHARTS_SQL"."ID" IS '编号';

   COMMENT ON COLUMN "WJZ"."ECHARTS_SQL"."OPT_ID" IS '外键';

   COMMENT ON COLUMN "WJZ"."ECHARTS_SQL"."NAME" IS '数据名称';

   COMMENT ON COLUMN "WJZ"."ECHARTS_SQL"."TYPE" IS '图表类型';

   COMMENT ON COLUMN "WJZ"."ECHARTS_SQL"."SQL" IS 'sql';

   COMMENT ON COLUMN "WJZ"."ECHARTS_SQL"."STATUS" IS '1:启用,0;禁用';

   COMMENT ON COLUMN "WJZ"."ECHARTS_SQL"."CREATE_TIME" IS '创建时间';

   COMMENT ON COLUMN "WJZ"."ECHARTS_SQL"."SORT" IS '排序';

   COMMENT ON COLUMN "WJZ"."ECHARTS_SQL"."RADIUS" IS '饼图半径';

   COMMENT ON COLUMN "WJZ"."ECHARTS_SQL"."SQL_PARAM" IS 'sql参数';

   COMMENT ON COLUMN "WJZ"."ECHARTS_SQL"."Y_TYPE" IS '0:value,1:自定义';
--------------------------------------------------------
--  DDL for Index ECHARTS_SQL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WJZ"."ECHARTS_SQL_PK" ON "WJZ"."ECHARTS_SQL" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ECHARTS_SQL
--------------------------------------------------------

  ALTER TABLE "WJZ"."ECHARTS_SQL" ADD CONSTRAINT "ECHARTS_SQL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;

  ALTER TABLE "WJZ"."ECHARTS_SQL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger TRIG_ECHARTS_SQL
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WJZ"."TRIG_ECHARTS_SQL"
   before insert on "WJZ"."ECHARTS_SQL"
   for each row
begin
   if inserting then
      if :NEW."ID" is null then
         select S_ECHARTS_SQL.nextval into :NEW."ID" from dual;
      end if;
   end if;
end;


/
ALTER TRIGGER "WJZ"."TRIG_ECHARTS_SQL" ENABLE;
