spring:
  profiles:
    active: mysql
  http.encoding.charset:  utf8
  mvc:
   static-path-pattern: /static/**
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  #开启ehcache缓存,指定主配置文件
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml


server:
  tomcat:
    max-http-post-size: 20791520
  port: 82

logging.level.com.zzhy: debug